# AutoTransform
# Large scale, component based code modification library
#
# Licensed under the MIT License <http://opensource.org/licenses/MIT>
# SPDX-License-Identifier: MIT
# Copyright (c) 2022-present Nathan Rockenbach <http://github.com/nathro>

name: Update AutoTransform

on:
  workflow_dispatch:
    inputs:
      change:
        description: "A JSON encoded Change to update"
        required: true
        type: string

jobs:
  update-autotransform:
    runs-on: ubuntu-latest
    name: Update
    steps:
    - uses: actions/checkout@v2
    - name: Set up git user
      run: |
        git config --global user.name "AutoTransform Bot"
        git config --global user.email "nathro.autotransform@gmail.com"
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Update pip
      run: pip install --upgrade pip
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Update AutoTransform
      run: python3 -m autotransform.scripts.main update --verbose --environment AUTO_TRANSFORM_CHANGE
      env:
        PYTHONPATH: /home/runner/work/AutoTransform/AutoTransform/src/python
        AUTO_TRANSFORM_CONFIG: environment
        AUTO_TRANSFORM_CREDENTIALS_GITHUB_TOKEN: ${{ secrets.AUTO_TRANSFORM_BOT_GITHUB_TOKEN }}
        AUTO_TRANSFORM_CHANGE: ${{ github.event.inputs.change }}