name: Check pylint

on: push

jobs:
  pylint:
    runs-on: ubuntu-latest
    name: pylint
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        pip install GitPython
        pip install PyGithub
        pip install typing-extensions
        pip install colorama

        pip install pytest
        pip install mock
    - name: Check pytest
      run: |
        pytest tests/
      env:
        PYTHONPATH: /home/runner/work/AutoTransform/AutoTransform/
        AUTO_TRANSFORM_CONFIG: environment
        AUTO_TRANSFORM_CREDENTIALS_GITHUB_TOKEN: ${{ github.token }}