name: Release

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    name: Validate and publish package
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        pip install GitPython
        pip install PyGithub
        pip install typing-extensions
        pip install colorama
        pip install types-colorama

        pip install mypy
        pip install pytest
        pip install mock
        pip install pylint

        pip install build
        pip install twine
    - name: Check mypy
      run: |
        mypy autotransform/
    - name: Check pytest
      run: |
        pytest tests/
      env:
        PYTHONPATH: /home/runner/work/AutoTransform/AutoTransform/
        AUTO_TRANSFORM_CONFIG: environment
        AUTO_TRANSFORM_CREDENTIALS_GITHUB_TOKEN: ${{ github.token }}
    - name: Check pylint
      run: |
        pylint autotransform/ --enable=W0611,R0201,R0902,R0903,R0913,R1732 --disable=R0801
    - name: Build
      run: |
        python3 -m build
    - name: Publish
      run: |
        python3 -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}
        TWINE_REPOSITORY: pypi